#!/bin/bash

exec &> /dev/null
export BROWSER = firefox
while read -r arg; do
	# first try matching by filename or pathname
	case "${arg,,}" in
		http*)
			firefox "$arg" &
			;;
		[^/]*) # doesn't start with '/'
			fish -c "$arg" &
			;;
		*.txt)
			$TERMINAL $EDITOR "$arg" &
			;;
		*.pdf | *.epub)
			mupdf "$arg" &
			;;
		*.mp3)
			$TERMINAL mpg123 -opulse "$arg" &
			;;
		*.od[tsp]|*.doc|*.docx|*.ppt|*.pptx|*.xls|*.xlsx)
			libreoffice "$arg" &
			;;
		*)
			# then try matching by mimetype
			mimetype=$(file -Lb --mime-type "$arg")
			case "$mimetype" in
				text/html)
					$BROWSER "$arg" &
					;;
				image/*)
					sxiv "$arg" &
					;;
				*)
					exit 1
					;;
			esac
			;;
	esac
done
